[package]
name = "zksync_os_interface"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
alloy-consensus = { workspace = true, default-features = false }
alloy-primitives = { workspace = true, default-features = false }
zksync_os_types = { workspace = true, default-features = false }

[features]
default = ["std", "serde"]
std = [
    "alloy-consensus/std",
    "alloy-primitives/std",
    "zksync_os_types/std",
]
serde = [
    "alloy-consensus/serde",
    "alloy-primitives/serde",
    "zksync_os_types/serde",
]
# Enables support for single core platforms without atomic CAS.
unsafe-single-core-cas = ["zksync_os_types/unsafe-single-core-cas"]
