[package]
name = "zksync_os_interface"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
alloy = { workspace = true, default-features = false, features = ["consensus"] }
zksync_os_types = { workspace = true, default-features = false }

[features]
default = ["serde"]
serde = [
    "alloy/serde",
    "zksync_os_types/serde",
]
# Use portable-atomic crate to support platforms without atomic CAS.
portable-atomic = ["zksync_os_types/portable-atomic"]
